// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gommerce/iam/v1beta/devices.proto

package iam_v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatchDeviceRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TraceCode     string                  `protobuf:"bytes,1,opt,name=trace_code,json=traceCode,proto3" json:"trace_code,omitempty"`
	PushToken     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	Metadata      map[string]string       `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchDeviceRequest) Reset() {
	*x = PatchDeviceRequest{}
	mi := &file_gommerce_iam_v1beta_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchDeviceRequest) ProtoMessage() {}

func (x *PatchDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchDeviceRequest.ProtoReflect.Descriptor instead.
func (*PatchDeviceRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_devices_proto_rawDescGZIP(), []int{0}
}

func (x *PatchDeviceRequest) GetTraceCode() string {
	if x != nil {
		return x.TraceCode
	}
	return ""
}

func (x *PatchDeviceRequest) GetPushToken() *wrapperspb.StringValue {
	if x != nil {
		return x.PushToken
	}
	return nil
}

func (x *PatchDeviceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PatchDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchDeviceResponse) Reset() {
	*x = PatchDeviceResponse{}
	mi := &file_gommerce_iam_v1beta_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchDeviceResponse) ProtoMessage() {}

func (x *PatchDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchDeviceResponse.ProtoReflect.Descriptor instead.
func (*PatchDeviceResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_devices_proto_rawDescGZIP(), []int{1}
}

var File_gommerce_iam_v1beta_devices_proto protoreflect.FileDescriptor

const file_gommerce_iam_v1beta_devices_proto_rawDesc = "" +
	"\n" +
	"!gommerce/iam/v1beta/devices.proto\x12\x13gommerce.iam.v1beta\x1a\x1egoogle/protobuf/wrappers.proto\"\x80\x02\n" +
	"\x12PatchDeviceRequest\x12\x1d\n" +
	"\n" +
	"trace_code\x18\x01 \x01(\tR\ttraceCode\x12;\n" +
	"\n" +
	"push_token\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\tpushToken\x12Q\n" +
	"\bmetadata\x18\x03 \x03(\v25.gommerce.iam.v1beta.PatchDeviceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13PatchDeviceResponse2t\n" +
	"\x0eDevicesService\x12b\n" +
	"\vPatchDevice\x12'.gommerce.iam.v1beta.PatchDeviceRequest\x1a(.gommerce.iam.v1beta.PatchDeviceResponse\"\x00B\x82\x01\n" +
	"#io.choral.gommerce.proto.iam.v1betaZ?github.com/choral-io/gommerce-protobuf-go/iam/v1beta;iam_v1beta\xaa\x02\x19Gommerce.Proto.IAM.V1Betab\x06proto3"

var (
	file_gommerce_iam_v1beta_devices_proto_rawDescOnce sync.Once
	file_gommerce_iam_v1beta_devices_proto_rawDescData []byte
)

func file_gommerce_iam_v1beta_devices_proto_rawDescGZIP() []byte {
	file_gommerce_iam_v1beta_devices_proto_rawDescOnce.Do(func() {
		file_gommerce_iam_v1beta_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_devices_proto_rawDesc), len(file_gommerce_iam_v1beta_devices_proto_rawDesc)))
	})
	return file_gommerce_iam_v1beta_devices_proto_rawDescData
}

var file_gommerce_iam_v1beta_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gommerce_iam_v1beta_devices_proto_goTypes = []any{
	(*PatchDeviceRequest)(nil),     // 0: gommerce.iam.v1beta.PatchDeviceRequest
	(*PatchDeviceResponse)(nil),    // 1: gommerce.iam.v1beta.PatchDeviceResponse
	nil,                            // 2: gommerce.iam.v1beta.PatchDeviceRequest.MetadataEntry
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_gommerce_iam_v1beta_devices_proto_depIdxs = []int32{
	3, // 0: gommerce.iam.v1beta.PatchDeviceRequest.push_token:type_name -> google.protobuf.StringValue
	2, // 1: gommerce.iam.v1beta.PatchDeviceRequest.metadata:type_name -> gommerce.iam.v1beta.PatchDeviceRequest.MetadataEntry
	0, // 2: gommerce.iam.v1beta.DevicesService.PatchDevice:input_type -> gommerce.iam.v1beta.PatchDeviceRequest
	1, // 3: gommerce.iam.v1beta.DevicesService.PatchDevice:output_type -> gommerce.iam.v1beta.PatchDeviceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gommerce_iam_v1beta_devices_proto_init() }
func file_gommerce_iam_v1beta_devices_proto_init() {
	if File_gommerce_iam_v1beta_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_devices_proto_rawDesc), len(file_gommerce_iam_v1beta_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gommerce_iam_v1beta_devices_proto_goTypes,
		DependencyIndexes: file_gommerce_iam_v1beta_devices_proto_depIdxs,
		MessageInfos:      file_gommerce_iam_v1beta_devices_proto_msgTypes,
	}.Build()
	File_gommerce_iam_v1beta_devices_proto = out.File
	file_gommerce_iam_v1beta_devices_proto_goTypes = nil
	file_gommerce_iam_v1beta_devices_proto_depIdxs = nil
}
