// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gommerce/iam/v1beta/devices.proto

package iam_v1beta

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PatchDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchDeviceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchDeviceRequestMultiError, or nil if none found.
func (m *PatchDeviceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchDeviceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TraceCode

	if all {
		switch v := interface{}(m.GetPushToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PatchDeviceRequestValidationError{
					field:  "PushToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PatchDeviceRequestValidationError{
					field:  "PushToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPushToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PatchDeviceRequestValidationError{
				field:  "PushToken",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Metadata

	if len(errors) > 0 {
		return PatchDeviceRequestMultiError(errors)
	}

	return nil
}

// PatchDeviceRequestMultiError is an error wrapping multiple validation errors
// returned by PatchDeviceRequest.ValidateAll() if the designated constraints
// aren't met.
type PatchDeviceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchDeviceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchDeviceRequestMultiError) AllErrors() []error { return m }

// PatchDeviceRequestValidationError is the validation error returned by
// PatchDeviceRequest.Validate if the designated constraints aren't met.
type PatchDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchDeviceRequestValidationError) ErrorName() string {
	return "PatchDeviceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PatchDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchDeviceRequestValidationError{}

// Validate checks the field values on PatchDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PatchDeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchDeviceResponseMultiError, or nil if none found.
func (m *PatchDeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchDeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PatchDeviceResponseMultiError(errors)
	}

	return nil
}

// PatchDeviceResponseMultiError is an error wrapping multiple validation
// errors returned by PatchDeviceResponse.ValidateAll() if the designated
// constraints aren't met.
type PatchDeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchDeviceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchDeviceResponseMultiError) AllErrors() []error { return m }

// PatchDeviceResponseValidationError is the validation error returned by
// PatchDeviceResponse.Validate if the designated constraints aren't met.
type PatchDeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchDeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchDeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchDeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchDeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchDeviceResponseValidationError) ErrorName() string {
	return "PatchDeviceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PatchDeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchDeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchDeviceResponseValidationError{}
