// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gommerce/iam/v1beta/realms.proto

package iam_v1beta

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Realm struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Disabled      bool                    `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Immutable     bool                    `protobuf:"varint,3,opt,name=immutable,proto3" json:"immutable,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name          string                  `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                  `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Realm) Reset() {
	*x = Realm{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Realm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Realm) ProtoMessage() {}

func (x *Realm) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Realm.ProtoReflect.Descriptor instead.
func (*Realm) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{0}
}

func (x *Realm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Realm) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Realm) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *Realm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Realm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Realm) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Realm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Realm) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Realm) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type CreateRealmRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Disabled      bool                    `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                  `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmRequest) Reset() {
	*x = CreateRealmRequest{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmRequest) ProtoMessage() {}

func (x *CreateRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmRequest.ProtoReflect.Descriptor instead.
func (*CreateRealmRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRealmRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *CreateRealmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRealmRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRealmRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type CreateRealmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Realm                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRealmResponse) Reset() {
	*x = CreateRealmResponse{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmResponse) ProtoMessage() {}

func (x *CreateRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmResponse.ProtoReflect.Descriptor instead.
func (*CreateRealmResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRealmResponse) GetValue() *Realm {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetRealmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealmRequest) Reset() {
	*x = GetRealmRequest{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealmRequest) ProtoMessage() {}

func (x *GetRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealmRequest.ProtoReflect.Descriptor instead.
func (*GetRealmRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{3}
}

func (x *GetRealmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRealmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Realm                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealmResponse) Reset() {
	*x = GetRealmResponse{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealmResponse) ProtoMessage() {}

func (x *GetRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealmResponse.ProtoReflect.Descriptor instead.
func (*GetRealmResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{4}
}

func (x *GetRealmResponse) GetValue() *Realm {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListRealmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRealmsRequest) Reset() {
	*x = ListRealmsRequest{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRealmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRealmsRequest) ProtoMessage() {}

func (x *ListRealmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRealmsRequest.ProtoReflect.Descriptor instead.
func (*ListRealmsRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{5}
}

func (x *ListRealmsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRealmsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListRealmsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListRealmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Realm               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRealmsResponse) Reset() {
	*x = ListRealmsResponse{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRealmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRealmsResponse) ProtoMessage() {}

func (x *ListRealmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRealmsResponse.ProtoReflect.Descriptor instead.
func (*ListRealmsResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{6}
}

func (x *ListRealmsResponse) GetItems() []*Realm {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRealmsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRealmsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListRealmsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateRealmRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Disabled      bool                    `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                  `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRealmRequest) Reset() {
	*x = UpdateRealmRequest{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealmRequest) ProtoMessage() {}

func (x *UpdateRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealmRequest.ProtoReflect.Descriptor instead.
func (*UpdateRealmRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRealmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRealmRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UpdateRealmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRealmRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRealmRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type UpdateRealmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRealmResponse) Reset() {
	*x = UpdateRealmResponse{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealmResponse) ProtoMessage() {}

func (x *UpdateRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealmResponse.ProtoReflect.Descriptor instead.
func (*UpdateRealmResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{8}
}

type DeleteRealmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRealmRequest) Reset() {
	*x = DeleteRealmRequest{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRealmRequest) ProtoMessage() {}

func (x *DeleteRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRealmRequest.ProtoReflect.Descriptor instead.
func (*DeleteRealmRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRealmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRealmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRealmResponse) Reset() {
	*x = DeleteRealmResponse{}
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRealmResponse) ProtoMessage() {}

func (x *DeleteRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_realms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRealmResponse.ProtoReflect.Descriptor instead.
func (*DeleteRealmResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_realms_proto_rawDescGZIP(), []int{10}
}

var File_gommerce_iam_v1beta_realms_proto protoreflect.FileDescriptor

const file_gommerce_iam_v1beta_realms_proto_rawDesc = "" +
	"\n" +
	" gommerce/iam/v1beta/realms.proto\x12\x13gommerce.iam.v1beta\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\"\xec\x02\n" +
	"\x05Realm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12\x1c\n" +
	"\timmutable\x18\x03 \x01(\bR\timmutable\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\"\xa0\x01\n" +
	"\x12CreateRealmRequest\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescriptionJ\x04\b\x01\x10\x02\"G\n" +
	"\x13CreateRealmResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gommerce.iam.v1beta.RealmR\x05value\"!\n" +
	"\x0fGetRealmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10GetRealmResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gommerce.iam.v1beta.RealmR\x05value\"a\n" +
	"\x11ListRealmsRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12\x1b\n" +
	"\x04size\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04size\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"\x84\x01\n" +
	"\x12ListRealmsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.gommerce.iam.v1beta.RealmR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\xaa\x01\n" +
	"\x12UpdateRealmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\"\x15\n" +
	"\x13UpdateRealmResponse\"$\n" +
	"\x12DeleteRealmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteRealmResponse2\x83\x04\n" +
	"\rRealmsService\x12b\n" +
	"\vCreateRealm\x12'.gommerce.iam.v1beta.CreateRealmRequest\x1a(.gommerce.iam.v1beta.CreateRealmResponse\"\x00\x12\\\n" +
	"\bGetRealm\x12$.gommerce.iam.v1beta.GetRealmRequest\x1a%.gommerce.iam.v1beta.GetRealmResponse\"\x03\x90\x02\x01\x12b\n" +
	"\n" +
	"ListRealms\x12&.gommerce.iam.v1beta.ListRealmsRequest\x1a'.gommerce.iam.v1beta.ListRealmsResponse\"\x03\x90\x02\x01\x12e\n" +
	"\vUpdateRealm\x12'.gommerce.iam.v1beta.UpdateRealmRequest\x1a(.gommerce.iam.v1beta.UpdateRealmResponse\"\x03\x90\x02\x01\x12e\n" +
	"\vDeleteRealm\x12'.gommerce.iam.v1beta.DeleteRealmRequest\x1a(.gommerce.iam.v1beta.DeleteRealmResponse\"\x03\x90\x02\x01B\x82\x01\n" +
	"#io.choral.gommerce.proto.iam.v1betaZ?github.com/choral-io/gommerce-protobuf-go/iam/v1beta;iam_v1beta\xaa\x02\x19Gommerce.Proto.IAM.V1Betab\x06proto3"

var (
	file_gommerce_iam_v1beta_realms_proto_rawDescOnce sync.Once
	file_gommerce_iam_v1beta_realms_proto_rawDescData []byte
)

func file_gommerce_iam_v1beta_realms_proto_rawDescGZIP() []byte {
	file_gommerce_iam_v1beta_realms_proto_rawDescOnce.Do(func() {
		file_gommerce_iam_v1beta_realms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_realms_proto_rawDesc), len(file_gommerce_iam_v1beta_realms_proto_rawDesc)))
	})
	return file_gommerce_iam_v1beta_realms_proto_rawDescData
}

var file_gommerce_iam_v1beta_realms_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gommerce_iam_v1beta_realms_proto_goTypes = []any{
	(*Realm)(nil),                  // 0: gommerce.iam.v1beta.Realm
	(*CreateRealmRequest)(nil),     // 1: gommerce.iam.v1beta.CreateRealmRequest
	(*CreateRealmResponse)(nil),    // 2: gommerce.iam.v1beta.CreateRealmResponse
	(*GetRealmRequest)(nil),        // 3: gommerce.iam.v1beta.GetRealmRequest
	(*GetRealmResponse)(nil),       // 4: gommerce.iam.v1beta.GetRealmResponse
	(*ListRealmsRequest)(nil),      // 5: gommerce.iam.v1beta.ListRealmsRequest
	(*ListRealmsResponse)(nil),     // 6: gommerce.iam.v1beta.ListRealmsResponse
	(*UpdateRealmRequest)(nil),     // 7: gommerce.iam.v1beta.UpdateRealmRequest
	(*UpdateRealmResponse)(nil),    // 8: gommerce.iam.v1beta.UpdateRealmResponse
	(*DeleteRealmRequest)(nil),     // 9: gommerce.iam.v1beta.DeleteRealmRequest
	(*DeleteRealmResponse)(nil),    // 10: gommerce.iam.v1beta.DeleteRealmResponse
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 12: google.protobuf.StringValue
}
var file_gommerce_iam_v1beta_realms_proto_depIdxs = []int32{
	11, // 0: gommerce.iam.v1beta.Realm.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: gommerce.iam.v1beta.Realm.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: gommerce.iam.v1beta.Realm.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 3: gommerce.iam.v1beta.Realm.description:type_name -> google.protobuf.StringValue
	12, // 4: gommerce.iam.v1beta.CreateRealmRequest.description:type_name -> google.protobuf.StringValue
	0,  // 5: gommerce.iam.v1beta.CreateRealmResponse.value:type_name -> gommerce.iam.v1beta.Realm
	0,  // 6: gommerce.iam.v1beta.GetRealmResponse.value:type_name -> gommerce.iam.v1beta.Realm
	0,  // 7: gommerce.iam.v1beta.ListRealmsResponse.items:type_name -> gommerce.iam.v1beta.Realm
	12, // 8: gommerce.iam.v1beta.UpdateRealmRequest.description:type_name -> google.protobuf.StringValue
	1,  // 9: gommerce.iam.v1beta.RealmsService.CreateRealm:input_type -> gommerce.iam.v1beta.CreateRealmRequest
	3,  // 10: gommerce.iam.v1beta.RealmsService.GetRealm:input_type -> gommerce.iam.v1beta.GetRealmRequest
	5,  // 11: gommerce.iam.v1beta.RealmsService.ListRealms:input_type -> gommerce.iam.v1beta.ListRealmsRequest
	7,  // 12: gommerce.iam.v1beta.RealmsService.UpdateRealm:input_type -> gommerce.iam.v1beta.UpdateRealmRequest
	9,  // 13: gommerce.iam.v1beta.RealmsService.DeleteRealm:input_type -> gommerce.iam.v1beta.DeleteRealmRequest
	2,  // 14: gommerce.iam.v1beta.RealmsService.CreateRealm:output_type -> gommerce.iam.v1beta.CreateRealmResponse
	4,  // 15: gommerce.iam.v1beta.RealmsService.GetRealm:output_type -> gommerce.iam.v1beta.GetRealmResponse
	6,  // 16: gommerce.iam.v1beta.RealmsService.ListRealms:output_type -> gommerce.iam.v1beta.ListRealmsResponse
	8,  // 17: gommerce.iam.v1beta.RealmsService.UpdateRealm:output_type -> gommerce.iam.v1beta.UpdateRealmResponse
	10, // 18: gommerce.iam.v1beta.RealmsService.DeleteRealm:output_type -> gommerce.iam.v1beta.DeleteRealmResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_gommerce_iam_v1beta_realms_proto_init() }
func file_gommerce_iam_v1beta_realms_proto_init() {
	if File_gommerce_iam_v1beta_realms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_realms_proto_rawDesc), len(file_gommerce_iam_v1beta_realms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gommerce_iam_v1beta_realms_proto_goTypes,
		DependencyIndexes: file_gommerce_iam_v1beta_realms_proto_depIdxs,
		MessageInfos:      file_gommerce_iam_v1beta_realms_proto_msgTypes,
	}.Build()
	File_gommerce_iam_v1beta_realms_proto = out.File
	file_gommerce_iam_v1beta_realms_proto_goTypes = nil
	file_gommerce_iam_v1beta_realms_proto_depIdxs = nil
}
