// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gommerce/iam/v1beta/realms.proto

package iam_v1beta

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Realm with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Realm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Realm with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RealmMultiError, or nil if none found.
func (m *Realm) ValidateAll() error {
	return m.validate(true)
}

func (m *Realm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Disabled

	// no validation rules for Immutable

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RealmValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RealmValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RealmValidationError{
				field:  "DeletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Name

	// no validation rules for Title

	if all {
		switch v := interface{}(m.GetDescription()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RealmValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDescription()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RealmValidationError{
				field:  "Description",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RealmMultiError(errors)
	}

	return nil
}

// RealmMultiError is an error wrapping multiple validation errors returned by
// Realm.ValidateAll() if the designated constraints aren't met.
type RealmMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RealmMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RealmMultiError) AllErrors() []error { return m }

// RealmValidationError is the validation error returned by Realm.Validate if
// the designated constraints aren't met.
type RealmValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RealmValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RealmValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RealmValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RealmValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RealmValidationError) ErrorName() string { return "RealmValidationError" }

// Error satisfies the builtin error interface
func (e RealmValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRealm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RealmValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RealmValidationError{}

// Validate checks the field values on CreateRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRealmRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRealmRequestMultiError, or nil if none found.
func (m *CreateRealmRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRealmRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Disabled

	// no validation rules for Name

	// no validation rules for Title

	if all {
		switch v := interface{}(m.GetDescription()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRealmRequestValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRealmRequestValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDescription()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRealmRequestValidationError{
				field:  "Description",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRealmRequestMultiError(errors)
	}

	return nil
}

// CreateRealmRequestMultiError is an error wrapping multiple validation errors
// returned by CreateRealmRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateRealmRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRealmRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRealmRequestMultiError) AllErrors() []error { return m }

// CreateRealmRequestValidationError is the validation error returned by
// CreateRealmRequest.Validate if the designated constraints aren't met.
type CreateRealmRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRealmRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRealmRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRealmRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRealmRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRealmRequestValidationError) ErrorName() string {
	return "CreateRealmRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRealmRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRealmRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRealmRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRealmRequestValidationError{}

// Validate checks the field values on CreateRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRealmResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRealmResponseMultiError, or nil if none found.
func (m *CreateRealmResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRealmResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetValue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRealmResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRealmResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRealmResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRealmResponseMultiError(errors)
	}

	return nil
}

// CreateRealmResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRealmResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRealmResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRealmResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRealmResponseMultiError) AllErrors() []error { return m }

// CreateRealmResponseValidationError is the validation error returned by
// CreateRealmResponse.Validate if the designated constraints aren't met.
type CreateRealmResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRealmResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRealmResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRealmResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRealmResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRealmResponseValidationError) ErrorName() string {
	return "CreateRealmResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRealmResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRealmResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRealmResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRealmResponseValidationError{}

// Validate checks the field values on GetRealmRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRealmRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRealmRequestMultiError, or nil if none found.
func (m *GetRealmRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRealmRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetRealmRequestMultiError(errors)
	}

	return nil
}

// GetRealmRequestMultiError is an error wrapping multiple validation errors
// returned by GetRealmRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRealmRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRealmRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRealmRequestMultiError) AllErrors() []error { return m }

// GetRealmRequestValidationError is the validation error returned by
// GetRealmRequest.Validate if the designated constraints aren't met.
type GetRealmRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRealmRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRealmRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRealmRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRealmRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRealmRequestValidationError) ErrorName() string { return "GetRealmRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetRealmRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRealmRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRealmRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRealmRequestValidationError{}

// Validate checks the field values on GetRealmResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRealmResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRealmResponseMultiError, or nil if none found.
func (m *GetRealmResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRealmResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetValue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRealmResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRealmResponseValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRealmResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRealmResponseMultiError(errors)
	}

	return nil
}

// GetRealmResponseMultiError is an error wrapping multiple validation errors
// returned by GetRealmResponse.ValidateAll() if the designated constraints
// aren't met.
type GetRealmResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRealmResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRealmResponseMultiError) AllErrors() []error { return m }

// GetRealmResponseValidationError is the validation error returned by
// GetRealmResponse.Validate if the designated constraints aren't met.
type GetRealmResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRealmResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRealmResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRealmResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRealmResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRealmResponseValidationError) ErrorName() string { return "GetRealmResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetRealmResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRealmResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRealmResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRealmResponseValidationError{}

// Validate checks the field values on ListRealmsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListRealmsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRealmsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRealmsRequestMultiError, or nil if none found.
func (m *ListRealmsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRealmsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Sort

	if len(errors) > 0 {
		return ListRealmsRequestMultiError(errors)
	}

	return nil
}

// ListRealmsRequestMultiError is an error wrapping multiple validation errors
// returned by ListRealmsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListRealmsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRealmsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRealmsRequestMultiError) AllErrors() []error { return m }

// ListRealmsRequestValidationError is the validation error returned by
// ListRealmsRequest.Validate if the designated constraints aren't met.
type ListRealmsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRealmsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRealmsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRealmsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRealmsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRealmsRequestValidationError) ErrorName() string {
	return "ListRealmsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRealmsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRealmsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRealmsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRealmsRequestValidationError{}

// Validate checks the field values on ListRealmsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRealmsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRealmsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRealmsResponseMultiError, or nil if none found.
func (m *ListRealmsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRealmsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRealmsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRealmsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRealmsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Total

	if len(errors) > 0 {
		return ListRealmsResponseMultiError(errors)
	}

	return nil
}

// ListRealmsResponseMultiError is an error wrapping multiple validation errors
// returned by ListRealmsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListRealmsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRealmsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRealmsResponseMultiError) AllErrors() []error { return m }

// ListRealmsResponseValidationError is the validation error returned by
// ListRealmsResponse.Validate if the designated constraints aren't met.
type ListRealmsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRealmsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRealmsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRealmsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRealmsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRealmsResponseValidationError) ErrorName() string {
	return "ListRealmsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRealmsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRealmsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRealmsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRealmsResponseValidationError{}

// Validate checks the field values on UpdateRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRealmRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRealmRequestMultiError, or nil if none found.
func (m *UpdateRealmRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRealmRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Disabled

	// no validation rules for Name

	// no validation rules for Title

	if all {
		switch v := interface{}(m.GetDescription()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRealmRequestValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRealmRequestValidationError{
					field:  "Description",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDescription()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRealmRequestValidationError{
				field:  "Description",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRealmRequestMultiError(errors)
	}

	return nil
}

// UpdateRealmRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateRealmRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateRealmRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRealmRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRealmRequestMultiError) AllErrors() []error { return m }

// UpdateRealmRequestValidationError is the validation error returned by
// UpdateRealmRequest.Validate if the designated constraints aren't met.
type UpdateRealmRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRealmRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRealmRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRealmRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRealmRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRealmRequestValidationError) ErrorName() string {
	return "UpdateRealmRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRealmRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRealmRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRealmRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRealmRequestValidationError{}

// Validate checks the field values on UpdateRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRealmResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRealmResponseMultiError, or nil if none found.
func (m *UpdateRealmResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRealmResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateRealmResponseMultiError(errors)
	}

	return nil
}

// UpdateRealmResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateRealmResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateRealmResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRealmResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRealmResponseMultiError) AllErrors() []error { return m }

// UpdateRealmResponseValidationError is the validation error returned by
// UpdateRealmResponse.Validate if the designated constraints aren't met.
type UpdateRealmResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRealmResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRealmResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRealmResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRealmResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRealmResponseValidationError) ErrorName() string {
	return "UpdateRealmResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRealmResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRealmResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRealmResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRealmResponseValidationError{}

// Validate checks the field values on DeleteRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRealmRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRealmRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRealmRequestMultiError, or nil if none found.
func (m *DeleteRealmRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRealmRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteRealmRequestMultiError(errors)
	}

	return nil
}

// DeleteRealmRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteRealmRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteRealmRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRealmRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRealmRequestMultiError) AllErrors() []error { return m }

// DeleteRealmRequestValidationError is the validation error returned by
// DeleteRealmRequest.Validate if the designated constraints aren't met.
type DeleteRealmRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRealmRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRealmRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRealmRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRealmRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRealmRequestValidationError) ErrorName() string {
	return "DeleteRealmRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRealmRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRealmRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRealmRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRealmRequestValidationError{}

// Validate checks the field values on DeleteRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRealmResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRealmResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRealmResponseMultiError, or nil if none found.
func (m *DeleteRealmResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRealmResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteRealmResponseMultiError(errors)
	}

	return nil
}

// DeleteRealmResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteRealmResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteRealmResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRealmResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRealmResponseMultiError) AllErrors() []error { return m }

// DeleteRealmResponseValidationError is the validation error returned by
// DeleteRealmResponse.Validate if the designated constraints aren't met.
type DeleteRealmResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRealmResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRealmResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRealmResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRealmResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRealmResponseValidationError) ErrorName() string {
	return "DeleteRealmResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRealmResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRealmResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRealmResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRealmResponseValidationError{}
