// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gommerce/iam/v1beta/users.proto

package iam_v1beta

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	gender "github.com/choral-io/gommerce-protobuf-go/types/v1/gender"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Id                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Realm              string                  `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Disabled           bool                    `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Approved           bool                    `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	Verified           bool                    `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	Immutable          bool                    `protobuf:"varint,6,opt,name=immutable,proto3" json:"immutable,omitempty"`
	CreatedAt          *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt          *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ExpiresAt          *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	FirstLoginTime     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=first_login_time,json=firstLoginTime,proto3" json:"first_login_time,omitempty"`
	LastActiveTime     *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=last_active_time,json=lastActiveTime,proto3" json:"last_active_time,omitempty"`
	Flags              int64                   `protobuf:"varint,13,opt,name=flags,proto3" json:"flags,omitempty"`
	Attributes         map[string]string       `protobuf:"bytes,14,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description        *wrapperspb.StringValue `protobuf:"bytes,25,opt,name=description,proto3" json:"description,omitempty"`
	MaskedPhoneNumber  *wrapperspb.StringValue `protobuf:"bytes,26,opt,name=masked_phone_number,json=maskedPhoneNumber,proto3" json:"masked_phone_number,omitempty"`
	MaskedEmailAddress *wrapperspb.StringValue `protobuf:"bytes,27,opt,name=masked_email_address,json=maskedEmailAddress,proto3" json:"masked_email_address,omitempty"`
	Creator            *User                   `protobuf:"bytes,38,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *User) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *User) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *User) GetFirstLoginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstLoginTime
	}
	return nil
}

func (x *User) GetLastActiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveTime
	}
	return nil
}

func (x *User) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *User) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *User) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *User) GetMaskedPhoneNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.MaskedPhoneNumber
	}
	return nil
}

func (x *User) GetMaskedEmailAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.MaskedEmailAddress
	}
	return nil
}

func (x *User) GetCreator() *User {
	if x != nil {
		return x.Creator
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Realm         string                  `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
	Username      string                  `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Gender        gender.Gender           `protobuf:"varint,6,opt,name=gender,proto3,enum=gommerce.types.v1.Gender" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() *wrapperspb.StringValue {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *RegisterRequest) GetAvatarUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *RegisterRequest) GetGender() gender.Gender {
	if x != nil {
		return x.Gender
	}
	return gender.Gender(0)
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListUsersRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{5}
}

type GetIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Scope         []string               `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityResponse) Reset() {
	*x = GetIdentityResponse{}
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityResponse) ProtoMessage() {}

func (x *GetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_iam_v1beta_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_iam_v1beta_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdentityResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetIdentityResponse) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_gommerce_iam_v1beta_users_proto protoreflect.FileDescriptor

const file_gommerce_iam_v1beta_users_proto_rawDesc = "" +
	"\n" +
	"\x1fgommerce/iam/v1beta/users.proto\x12\x13gommerce.iam.v1beta\x1a\x1bbuf/validate/validate.proto\x1a\x1egommerce/types/v1/gender.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd5\a\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapproved\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\x12\x1c\n" +
	"\timmutable\x18\x06 \x01(\bR\timmutable\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12D\n" +
	"\x10first_login_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0efirstLoginTime\x12D\n" +
	"\x10last_active_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActiveTime\x12\x14\n" +
	"\x05flags\x18\r \x01(\x03R\x05flags\x12I\n" +
	"\n" +
	"attributes\x18\x0e \x03(\v2).gommerce.iam.v1beta.User.AttributesEntryR\n" +
	"attributes\x12>\n" +
	"\vdescription\x18\x19 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12L\n" +
	"\x13masked_phone_number\x18\x1a \x01(\v2\x1c.google.protobuf.StringValueR\x11maskedPhoneNumber\x12N\n" +
	"\x14masked_email_address\x18\x1b \x01(\v2\x1c.google.protobuf.StringValueR\x12maskedEmailAddress\x123\n" +
	"\acreator\x18& \x01(\v2\x19.gommerce.iam.v1beta.UserR\acreator\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0f\x10\x19J\x04\b\x1c\x10&\"\xc8\x02\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\x05realm\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x188R\x05realm\x12%\n" +
	"\busername\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x188R\busername\x12%\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x188R\bpassword\x12J\n" +
	"\fdisplay_name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\t\xbaH\x06r\x04\x10\x02\x18xR\vdisplayName\x12G\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB\n" +
	"\xbaH\ar\x05\x10\x00\x18\x80\x10R\tavatarUrl\x121\n" +
	"\x06gender\x18\x06 \x01(\x0e2\x19.gommerce.types.v1.GenderR\x06gender\"A\n" +
	"\x10RegisterResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.gommerce.iam.v1beta.UserR\x04user\"`\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x04page\x12\x1b\n" +
	"\x04size\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x04size\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"\x82\x01\n" +
	"\x11ListUsersResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.gommerce.iam.v1beta.UserR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x14\n" +
	"\x12GetIdentityRequest\"Z\n" +
	"\x13GetIdentityResponse\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.gommerce.iam.v1beta.UserR\x04user\x12\x14\n" +
	"\x05scope\x18\x02 \x03(\tR\x05scope2\xb4\x02\n" +
	"\fUsersService\x12\\\n" +
	"\bRegister\x12$.gommerce.iam.v1beta.RegisterRequest\x1a%.gommerce.iam.v1beta.RegisterResponse\"\x03\x90\x02\x02\x12_\n" +
	"\tListUsers\x12%.gommerce.iam.v1beta.ListUsersRequest\x1a&.gommerce.iam.v1beta.ListUsersResponse\"\x03\x90\x02\x01\x12e\n" +
	"\vGetIdentity\x12'.gommerce.iam.v1beta.GetIdentityRequest\x1a(.gommerce.iam.v1beta.GetIdentityResponse\"\x03\x90\x02\x01B\x82\x01\n" +
	"#io.choral.gommerce.proto.iam.v1betaZ?github.com/choral-io/gommerce-protobuf-go/iam/v1beta;iam_v1beta\xaa\x02\x19Gommerce.Proto.IAM.V1Betab\x06proto3"

var (
	file_gommerce_iam_v1beta_users_proto_rawDescOnce sync.Once
	file_gommerce_iam_v1beta_users_proto_rawDescData []byte
)

func file_gommerce_iam_v1beta_users_proto_rawDescGZIP() []byte {
	file_gommerce_iam_v1beta_users_proto_rawDescOnce.Do(func() {
		file_gommerce_iam_v1beta_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_users_proto_rawDesc), len(file_gommerce_iam_v1beta_users_proto_rawDesc)))
	})
	return file_gommerce_iam_v1beta_users_proto_rawDescData
}

var file_gommerce_iam_v1beta_users_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gommerce_iam_v1beta_users_proto_goTypes = []any{
	(*User)(nil),                   // 0: gommerce.iam.v1beta.User
	(*RegisterRequest)(nil),        // 1: gommerce.iam.v1beta.RegisterRequest
	(*RegisterResponse)(nil),       // 2: gommerce.iam.v1beta.RegisterResponse
	(*ListUsersRequest)(nil),       // 3: gommerce.iam.v1beta.ListUsersRequest
	(*ListUsersResponse)(nil),      // 4: gommerce.iam.v1beta.ListUsersResponse
	(*GetIdentityRequest)(nil),     // 5: gommerce.iam.v1beta.GetIdentityRequest
	(*GetIdentityResponse)(nil),    // 6: gommerce.iam.v1beta.GetIdentityResponse
	nil,                            // 7: gommerce.iam.v1beta.User.AttributesEntry
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 9: google.protobuf.StringValue
	(gender.Gender)(0),             // 10: gommerce.types.v1.Gender
}
var file_gommerce_iam_v1beta_users_proto_depIdxs = []int32{
	8,  // 0: gommerce.iam.v1beta.User.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: gommerce.iam.v1beta.User.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: gommerce.iam.v1beta.User.deleted_at:type_name -> google.protobuf.Timestamp
	8,  // 3: gommerce.iam.v1beta.User.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 4: gommerce.iam.v1beta.User.first_login_time:type_name -> google.protobuf.Timestamp
	8,  // 5: gommerce.iam.v1beta.User.last_active_time:type_name -> google.protobuf.Timestamp
	7,  // 6: gommerce.iam.v1beta.User.attributes:type_name -> gommerce.iam.v1beta.User.AttributesEntry
	9,  // 7: gommerce.iam.v1beta.User.description:type_name -> google.protobuf.StringValue
	9,  // 8: gommerce.iam.v1beta.User.masked_phone_number:type_name -> google.protobuf.StringValue
	9,  // 9: gommerce.iam.v1beta.User.masked_email_address:type_name -> google.protobuf.StringValue
	0,  // 10: gommerce.iam.v1beta.User.creator:type_name -> gommerce.iam.v1beta.User
	9,  // 11: gommerce.iam.v1beta.RegisterRequest.display_name:type_name -> google.protobuf.StringValue
	9,  // 12: gommerce.iam.v1beta.RegisterRequest.avatar_url:type_name -> google.protobuf.StringValue
	10, // 13: gommerce.iam.v1beta.RegisterRequest.gender:type_name -> gommerce.types.v1.Gender
	0,  // 14: gommerce.iam.v1beta.RegisterResponse.user:type_name -> gommerce.iam.v1beta.User
	0,  // 15: gommerce.iam.v1beta.ListUsersResponse.items:type_name -> gommerce.iam.v1beta.User
	0,  // 16: gommerce.iam.v1beta.GetIdentityResponse.user:type_name -> gommerce.iam.v1beta.User
	1,  // 17: gommerce.iam.v1beta.UsersService.Register:input_type -> gommerce.iam.v1beta.RegisterRequest
	3,  // 18: gommerce.iam.v1beta.UsersService.ListUsers:input_type -> gommerce.iam.v1beta.ListUsersRequest
	5,  // 19: gommerce.iam.v1beta.UsersService.GetIdentity:input_type -> gommerce.iam.v1beta.GetIdentityRequest
	2,  // 20: gommerce.iam.v1beta.UsersService.Register:output_type -> gommerce.iam.v1beta.RegisterResponse
	4,  // 21: gommerce.iam.v1beta.UsersService.ListUsers:output_type -> gommerce.iam.v1beta.ListUsersResponse
	6,  // 22: gommerce.iam.v1beta.UsersService.GetIdentity:output_type -> gommerce.iam.v1beta.GetIdentityResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gommerce_iam_v1beta_users_proto_init() }
func file_gommerce_iam_v1beta_users_proto_init() {
	if File_gommerce_iam_v1beta_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gommerce_iam_v1beta_users_proto_rawDesc), len(file_gommerce_iam_v1beta_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gommerce_iam_v1beta_users_proto_goTypes,
		DependencyIndexes: file_gommerce_iam_v1beta_users_proto_depIdxs,
		MessageInfos:      file_gommerce_iam_v1beta_users_proto_msgTypes,
	}.Build()
	File_gommerce_iam_v1beta_users_proto = out.File
	file_gommerce_iam_v1beta_users_proto_goTypes = nil
	file_gommerce_iam_v1beta_users_proto_depIdxs = nil
}
