// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gommerce/chats/v1beta/chats.proto

package chats_v1beta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatsService_ListSessions_FullMethodName    = "/gommerce.chats.v1beta.ChatsService/ListSessions"
	ChatsService_DescribeSession_FullMethodName = "/gommerce.chats.v1beta.ChatsService/DescribeSession"
	ChatsService_ReadSession_FullMethodName     = "/gommerce.chats.v1beta.ChatsService/ReadSession"
	ChatsService_SendRecord_FullMethodName      = "/gommerce.chats.v1beta.ChatsService/SendRecord"
	ChatsService_ListRecords_FullMethodName     = "/gommerce.chats.v1beta.ChatsService/ListRecords"
	ChatsService_WatchRecords_FullMethodName    = "/gommerce.chats.v1beta.ChatsService/WatchRecords"
)

// ChatsServiceClient is the client API for ChatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatsServiceClient interface {
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DescribeSession(ctx context.Context, in *DescribeSessionRequest, opts ...grpc.CallOption) (*DescribeSessionResponse, error)
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error)
	SendRecord(ctx context.Context, in *SendRecordRequest, opts ...grpc.CallOption) (*SendRecordResponse, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error)
	WatchRecords(ctx context.Context, in *WatchRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRecordsResponse], error)
}

type chatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatsServiceClient(cc grpc.ClientConnInterface) ChatsServiceClient {
	return &chatsServiceClient{cc}
}

func (c *chatsServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, ChatsService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) DescribeSession(ctx context.Context, in *DescribeSessionRequest, opts ...grpc.CallOption) (*DescribeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeSessionResponse)
	err := c.cc.Invoke(ctx, ChatsService_DescribeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...grpc.CallOption) (*ReadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSessionResponse)
	err := c.cc.Invoke(ctx, ChatsService_ReadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) SendRecord(ctx context.Context, in *SendRecordRequest, opts ...grpc.CallOption) (*SendRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRecordResponse)
	err := c.cc.Invoke(ctx, ChatsService_SendRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResponse)
	err := c.cc.Invoke(ctx, ChatsService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsServiceClient) WatchRecords(ctx context.Context, in *WatchRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRecordsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatsService_ServiceDesc.Streams[0], ChatsService_WatchRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRecordsRequest, WatchRecordsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatsService_WatchRecordsClient = grpc.ServerStreamingClient[WatchRecordsResponse]

// ChatsServiceServer is the server API for ChatsService service.
// All implementations must embed UnimplementedChatsServiceServer
// for forward compatibility.
type ChatsServiceServer interface {
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DescribeSession(context.Context, *DescribeSessionRequest) (*DescribeSessionResponse, error)
	ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error)
	SendRecord(context.Context, *SendRecordRequest) (*SendRecordResponse, error)
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error)
	WatchRecords(*WatchRecordsRequest, grpc.ServerStreamingServer[WatchRecordsResponse]) error
	mustEmbedUnimplementedChatsServiceServer()
}

// UnimplementedChatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatsServiceServer struct{}

func (UnimplementedChatsServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedChatsServiceServer) DescribeSession(context.Context, *DescribeSessionRequest) (*DescribeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeSession not implemented")
}
func (UnimplementedChatsServiceServer) ReadSession(context.Context, *ReadSessionRequest) (*ReadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSession not implemented")
}
func (UnimplementedChatsServiceServer) SendRecord(context.Context, *SendRecordRequest) (*SendRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRecord not implemented")
}
func (UnimplementedChatsServiceServer) ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedChatsServiceServer) WatchRecords(*WatchRecordsRequest, grpc.ServerStreamingServer[WatchRecordsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchRecords not implemented")
}
func (UnimplementedChatsServiceServer) mustEmbedUnimplementedChatsServiceServer() {}
func (UnimplementedChatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeChatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatsServiceServer will
// result in compilation errors.
type UnsafeChatsServiceServer interface {
	mustEmbedUnimplementedChatsServiceServer()
}

func RegisterChatsServiceServer(s grpc.ServiceRegistrar, srv ChatsServiceServer) {
	// If the following call panics, it indicates UnimplementedChatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatsService_ServiceDesc, srv)
}

func _ChatsService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_DescribeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).DescribeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_DescribeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).DescribeSession(ctx, req.(*DescribeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_ReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).ReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_ReadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).ReadSession(ctx, req.(*ReadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_SendRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).SendRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_SendRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).SendRecord(ctx, req.(*SendRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatsService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatsService_WatchRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatsServiceServer).WatchRecords(m, &grpc.GenericServerStream[WatchRecordsRequest, WatchRecordsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatsService_WatchRecordsServer = grpc.ServerStreamingServer[WatchRecordsResponse]

// ChatsService_ServiceDesc is the grpc.ServiceDesc for ChatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gommerce.chats.v1beta.ChatsService",
	HandlerType: (*ChatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _ChatsService_ListSessions_Handler,
		},
		{
			MethodName: "DescribeSession",
			Handler:    _ChatsService_DescribeSession_Handler,
		},
		{
			MethodName: "ReadSession",
			Handler:    _ChatsService_ReadSession_Handler,
		},
		{
			MethodName: "SendRecord",
			Handler:    _ChatsService_SendRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _ChatsService_ListRecords_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRecords",
			Handler:       _ChatsService_WatchRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gommerce/chats/v1beta/chats.proto",
}
