// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: gommerce/utils/v1/utils.proto

package utils_v1

import (
	tsoffset "github.com/choral-io/gommerce-protobuf-go/types/v1/tsoffset"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MinValue int64  `protobuf:"varint,2,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue int64  `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
}

func (x *NextValueRequest) Reset() {
	*x = NextValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextValueRequest) ProtoMessage() {}

func (x *NextValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextValueRequest.ProtoReflect.Descriptor instead.
func (*NextValueRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{0}
}

func (x *NextValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NextValueRequest) GetMinValue() int64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *NextValueRequest) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type NextValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NextValueResponse) Reset() {
	*x = NextValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextValueResponse) ProtoMessage() {}

func (x *NextValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextValueResponse.ProtoReflect.Descriptor instead.
func (*NextValueResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{1}
}

func (x *NextValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NextValueResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NextHexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NextHexRequest) Reset() {
	*x = NextHexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextHexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHexRequest) ProtoMessage() {}

func (x *NextHexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHexRequest.ProtoReflect.Descriptor instead.
func (*NextHexRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{2}
}

type NextHexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NextHexResponse) Reset() {
	*x = NextHexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextHexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHexResponse) ProtoMessage() {}

func (x *NextHexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHexResponse.ProtoReflect.Descriptor instead.
func (*NextHexResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{3}
}

func (x *NextHexResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NextInt64Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NextInt64Request) Reset() {
	*x = NextInt64Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextInt64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextInt64Request) ProtoMessage() {}

func (x *NextInt64Request) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextInt64Request.ProtoReflect.Descriptor instead.
func (*NextInt64Request) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{4}
}

type NextInt64Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NextInt64Response) Reset() {
	*x = NextInt64Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextInt64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextInt64Response) ProtoMessage() {}

func (x *NextInt64Response) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextInt64Response.ProtoReflect.Descriptor instead.
func (*NextInt64Response) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{5}
}

func (x *NextInt64Response) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GeneratePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length  int32  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Symbols string `protobuf:"bytes,2,opt,name=symbols,proto3" json:"symbols,omitempty"`
}

func (x *GeneratePasswordRequest) Reset() {
	*x = GeneratePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePasswordRequest) ProtoMessage() {}

func (x *GeneratePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePasswordRequest.ProtoReflect.Descriptor instead.
func (*GeneratePasswordRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{6}
}

func (x *GeneratePasswordRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GeneratePasswordRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

type GeneratePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GeneratePasswordResponse) Reset() {
	*x = GeneratePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePasswordResponse) ProtoMessage() {}

func (x *GeneratePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePasswordResponse.ProtoReflect.Descriptor instead.
func (*GeneratePasswordResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{7}
}

func (x *GeneratePasswordResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HashPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HashPasswordRequest) Reset() {
	*x = HashPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordRequest) ProtoMessage() {}

func (x *HashPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordRequest.ProtoReflect.Descriptor instead.
func (*HashPasswordRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{8}
}

func (x *HashPasswordRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HashPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HashPasswordResponse) Reset() {
	*x = HashPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordResponse) ProtoMessage() {}

func (x *HashPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordResponse.ProtoReflect.Descriptor instead.
func (*HashPasswordResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{9}
}

func (x *HashPasswordResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ValidatePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashedPassword   string `protobuf:"bytes,1,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	ProvidedPassword string `protobuf:"bytes,2,opt,name=provided_password,json=providedPassword,proto3" json:"provided_password,omitempty"`
}

func (x *ValidatePasswordRequest) Reset() {
	*x = ValidatePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePasswordRequest) ProtoMessage() {}

func (x *ValidatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePasswordRequest.ProtoReflect.Descriptor instead.
func (*ValidatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{10}
}

func (x *ValidatePasswordRequest) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *ValidatePasswordRequest) GetProvidedPassword() string {
	if x != nil {
		return x.ProvidedPassword
	}
	return ""
}

type ValidatePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidatePasswordResponse) Reset() {
	*x = ValidatePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePasswordResponse) ProtoMessage() {}

func (x *ValidatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePasswordResponse.ProtoReflect.Descriptor instead.
func (*ValidatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{11}
}

func (x *ValidatePasswordResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GetDBNowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDBNowRequest) Reset() {
	*x = GetDBNowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDBNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBNowRequest) ProtoMessage() {}

func (x *GetDBNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBNowRequest.ProtoReflect.Descriptor instead.
func (*GetDBNowRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{12}
}

type GetDBNowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tsoffset.TimestampOffset `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetDBNowResponse) Reset() {
	*x = GetDBNowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDBNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDBNowResponse) ProtoMessage() {}

func (x *GetDBNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDBNowResponse.ProtoReflect.Descriptor instead.
func (*GetDBNowResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{13}
}

func (x *GetDBNowResponse) GetValue() *tsoffset.TimestampOffset {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetRedisNowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRedisNowRequest) Reset() {
	*x = GetRedisNowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedisNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisNowRequest) ProtoMessage() {}

func (x *GetRedisNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisNowRequest.ProtoReflect.Descriptor instead.
func (*GetRedisNowRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{14}
}

type GetRedisNowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tsoffset.TimestampOffset `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetRedisNowResponse) Reset() {
	*x = GetRedisNowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRedisNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisNowResponse) ProtoMessage() {}

func (x *GetRedisNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisNowResponse.ProtoReflect.Descriptor instead.
func (*GetRedisNowResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{15}
}

func (x *GetRedisNowResponse) GetValue() *tsoffset.TimestampOffset {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetUTCNowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUTCNowRequest) Reset() {
	*x = GetUTCNowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUTCNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUTCNowRequest) ProtoMessage() {}

func (x *GetUTCNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUTCNowRequest.ProtoReflect.Descriptor instead.
func (*GetUTCNowRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{16}
}

type GetUTCNowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tsoffset.TimestampOffset `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetUTCNowResponse) Reset() {
	*x = GetUTCNowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUTCNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUTCNowResponse) ProtoMessage() {}

func (x *GetUTCNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUTCNowResponse.ProtoReflect.Descriptor instead.
func (*GetUTCNowResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{17}
}

func (x *GetUTCNowResponse) GetValue() *tsoffset.TimestampOffset {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetLocalNowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLocalNowRequest) Reset() {
	*x = GetLocalNowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocalNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalNowRequest) ProtoMessage() {}

func (x *GetLocalNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalNowRequest.ProtoReflect.Descriptor instead.
func (*GetLocalNowRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{18}
}

type GetLocalNowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tsoffset.TimestampOffset `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetLocalNowResponse) Reset() {
	*x = GetLocalNowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocalNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalNowResponse) ProtoMessage() {}

func (x *GetLocalNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalNowResponse.ProtoReflect.Descriptor instead.
func (*GetLocalNowResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{19}
}

func (x *GetLocalNowResponse) GetValue() *tsoffset.TimestampOffset {
	if x != nil {
		return x.Value
	}
	return nil
}

type WatchLocalNowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchLocalNowRequest) Reset() {
	*x = WatchLocalNowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchLocalNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLocalNowRequest) ProtoMessage() {}

func (x *WatchLocalNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLocalNowRequest.ProtoReflect.Descriptor instead.
func (*WatchLocalNowRequest) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{20}
}

type WatchLocalNowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tsoffset.TimestampOffset `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WatchLocalNowResponse) Reset() {
	*x = WatchLocalNowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gommerce_utils_v1_utils_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchLocalNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLocalNowResponse) ProtoMessage() {}

func (x *WatchLocalNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gommerce_utils_v1_utils_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLocalNowResponse.ProtoReflect.Descriptor instead.
func (*WatchLocalNowResponse) Descriptor() ([]byte, []int) {
	return file_gommerce_utils_v1_utils_proto_rawDescGZIP(), []int{21}
}

func (x *WatchLocalNowResponse) GetValue() *tsoffset.TimestampOffset {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_gommerce_utils_v1_utils_proto protoreflect.FileDescriptor

var file_gommerce_utils_v1_utils_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73,
	0x2f, 0x76, 0x31, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x73, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a,
	0x10, 0x4e, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x09,
	0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x24, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x28, 0x00, 0x52, 0x08,
	0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x4e, 0x65, 0x78, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x78, 0x74, 0x48, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0f, 0x4e, 0x65, 0x78, 0x74, 0x48,
	0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x11, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x5d, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a,
	0x02, 0x20, 0x00, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x07, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x22, 0x30,
	0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x34, 0x0a, 0x13, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x30, 0x0a, 0x0f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x34, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x64, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x64,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x30, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x44, 0x42, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x44, 0x42, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4e, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x54, 0x43, 0x4e, 0x6f, 0x77, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x54, 0x43,
	0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x16, 0x0a, 0x14,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x6e, 0x0a, 0x0f, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x09, 0x4e, 0x65,
	0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x32, 0xc6, 0x01, 0x0a, 0x10, 0x53, 0x6e, 0x6f, 0x77,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x07,
	0x4e, 0x65, 0x78, 0x74, 0x48, 0x65, 0x78, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74,
	0x48, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x6d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e,
	0x65, 0x78, 0x74, 0x48, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03,
	0x90, 0x02, 0x01, 0x12, 0x5b, 0x0a, 0x09, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x23, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01,
	0x32, 0xdb, 0x02, 0x0a, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x70, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e,
	0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x64, 0x0a, 0x0c, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x70, 0x0a, 0x10,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x2a, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x67,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x32, 0xf9,
	0x03, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x42, 0x4e, 0x6f, 0x77, 0x12, 0x22,
	0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x42, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x42, 0x4e, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x61, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4e, 0x6f, 0x77, 0x12, 0x25, 0x2e, 0x67, 0x6f,
	0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4e,
	0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12,
	0x5b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x54, 0x43, 0x4e, 0x6f, 0x77, 0x12, 0x23, 0x2e, 0x67,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x54, 0x43, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69,
	0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x54, 0x43, 0x4e, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x61, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x12, 0x25, 0x2e, 0x67, 0x6f,
	0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74,
	0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e,
	0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12,
	0x69, 0x0a, 0x0d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77,
	0x12, 0x27, 0x2e, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e,
	0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x67, 0x6f, 0x6d, 0x6d,
	0x65, 0x72, 0x63, 0x65, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x30, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x61, 0x6c, 0x2d,
	0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gommerce_utils_v1_utils_proto_rawDescOnce sync.Once
	file_gommerce_utils_v1_utils_proto_rawDescData = file_gommerce_utils_v1_utils_proto_rawDesc
)

func file_gommerce_utils_v1_utils_proto_rawDescGZIP() []byte {
	file_gommerce_utils_v1_utils_proto_rawDescOnce.Do(func() {
		file_gommerce_utils_v1_utils_proto_rawDescData = protoimpl.X.CompressGZIP(file_gommerce_utils_v1_utils_proto_rawDescData)
	})
	return file_gommerce_utils_v1_utils_proto_rawDescData
}

var file_gommerce_utils_v1_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_gommerce_utils_v1_utils_proto_goTypes = []interface{}{
	(*NextValueRequest)(nil),         // 0: gommerce.utils.v1.NextValueRequest
	(*NextValueResponse)(nil),        // 1: gommerce.utils.v1.NextValueResponse
	(*NextHexRequest)(nil),           // 2: gommerce.utils.v1.NextHexRequest
	(*NextHexResponse)(nil),          // 3: gommerce.utils.v1.NextHexResponse
	(*NextInt64Request)(nil),         // 4: gommerce.utils.v1.NextInt64Request
	(*NextInt64Response)(nil),        // 5: gommerce.utils.v1.NextInt64Response
	(*GeneratePasswordRequest)(nil),  // 6: gommerce.utils.v1.GeneratePasswordRequest
	(*GeneratePasswordResponse)(nil), // 7: gommerce.utils.v1.GeneratePasswordResponse
	(*HashPasswordRequest)(nil),      // 8: gommerce.utils.v1.HashPasswordRequest
	(*HashPasswordResponse)(nil),     // 9: gommerce.utils.v1.HashPasswordResponse
	(*ValidatePasswordRequest)(nil),  // 10: gommerce.utils.v1.ValidatePasswordRequest
	(*ValidatePasswordResponse)(nil), // 11: gommerce.utils.v1.ValidatePasswordResponse
	(*GetDBNowRequest)(nil),          // 12: gommerce.utils.v1.GetDBNowRequest
	(*GetDBNowResponse)(nil),         // 13: gommerce.utils.v1.GetDBNowResponse
	(*GetRedisNowRequest)(nil),       // 14: gommerce.utils.v1.GetRedisNowRequest
	(*GetRedisNowResponse)(nil),      // 15: gommerce.utils.v1.GetRedisNowResponse
	(*GetUTCNowRequest)(nil),         // 16: gommerce.utils.v1.GetUTCNowRequest
	(*GetUTCNowResponse)(nil),        // 17: gommerce.utils.v1.GetUTCNowResponse
	(*GetLocalNowRequest)(nil),       // 18: gommerce.utils.v1.GetLocalNowRequest
	(*GetLocalNowResponse)(nil),      // 19: gommerce.utils.v1.GetLocalNowResponse
	(*WatchLocalNowRequest)(nil),     // 20: gommerce.utils.v1.WatchLocalNowRequest
	(*WatchLocalNowResponse)(nil),    // 21: gommerce.utils.v1.WatchLocalNowResponse
	(*tsoffset.TimestampOffset)(nil), // 22: gommerce.types.v1.TimestampOffset
}
var file_gommerce_utils_v1_utils_proto_depIdxs = []int32{
	22, // 0: gommerce.utils.v1.GetDBNowResponse.value:type_name -> gommerce.types.v1.TimestampOffset
	22, // 1: gommerce.utils.v1.GetRedisNowResponse.value:type_name -> gommerce.types.v1.TimestampOffset
	22, // 2: gommerce.utils.v1.GetUTCNowResponse.value:type_name -> gommerce.types.v1.TimestampOffset
	22, // 3: gommerce.utils.v1.GetLocalNowResponse.value:type_name -> gommerce.types.v1.TimestampOffset
	22, // 4: gommerce.utils.v1.WatchLocalNowResponse.value:type_name -> gommerce.types.v1.TimestampOffset
	0,  // 5: gommerce.utils.v1.SequenceService.NextValue:input_type -> gommerce.utils.v1.NextValueRequest
	2,  // 6: gommerce.utils.v1.SnowflakeService.NextHex:input_type -> gommerce.utils.v1.NextHexRequest
	4,  // 7: gommerce.utils.v1.SnowflakeService.NextInt64:input_type -> gommerce.utils.v1.NextInt64Request
	6,  // 8: gommerce.utils.v1.PasswordService.GeneratePassword:input_type -> gommerce.utils.v1.GeneratePasswordRequest
	8,  // 9: gommerce.utils.v1.PasswordService.HashPassword:input_type -> gommerce.utils.v1.HashPasswordRequest
	10, // 10: gommerce.utils.v1.PasswordService.ValidatePassword:input_type -> gommerce.utils.v1.ValidatePasswordRequest
	12, // 11: gommerce.utils.v1.DateTimeService.GetDBNow:input_type -> gommerce.utils.v1.GetDBNowRequest
	14, // 12: gommerce.utils.v1.DateTimeService.GetRedisNow:input_type -> gommerce.utils.v1.GetRedisNowRequest
	16, // 13: gommerce.utils.v1.DateTimeService.GetUTCNow:input_type -> gommerce.utils.v1.GetUTCNowRequest
	18, // 14: gommerce.utils.v1.DateTimeService.GetLocalNow:input_type -> gommerce.utils.v1.GetLocalNowRequest
	20, // 15: gommerce.utils.v1.DateTimeService.WatchLocalNow:input_type -> gommerce.utils.v1.WatchLocalNowRequest
	1,  // 16: gommerce.utils.v1.SequenceService.NextValue:output_type -> gommerce.utils.v1.NextValueResponse
	3,  // 17: gommerce.utils.v1.SnowflakeService.NextHex:output_type -> gommerce.utils.v1.NextHexResponse
	5,  // 18: gommerce.utils.v1.SnowflakeService.NextInt64:output_type -> gommerce.utils.v1.NextInt64Response
	7,  // 19: gommerce.utils.v1.PasswordService.GeneratePassword:output_type -> gommerce.utils.v1.GeneratePasswordResponse
	9,  // 20: gommerce.utils.v1.PasswordService.HashPassword:output_type -> gommerce.utils.v1.HashPasswordResponse
	11, // 21: gommerce.utils.v1.PasswordService.ValidatePassword:output_type -> gommerce.utils.v1.ValidatePasswordResponse
	13, // 22: gommerce.utils.v1.DateTimeService.GetDBNow:output_type -> gommerce.utils.v1.GetDBNowResponse
	15, // 23: gommerce.utils.v1.DateTimeService.GetRedisNow:output_type -> gommerce.utils.v1.GetRedisNowResponse
	17, // 24: gommerce.utils.v1.DateTimeService.GetUTCNow:output_type -> gommerce.utils.v1.GetUTCNowResponse
	19, // 25: gommerce.utils.v1.DateTimeService.GetLocalNow:output_type -> gommerce.utils.v1.GetLocalNowResponse
	21, // 26: gommerce.utils.v1.DateTimeService.WatchLocalNow:output_type -> gommerce.utils.v1.WatchLocalNowResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gommerce_utils_v1_utils_proto_init() }
func file_gommerce_utils_v1_utils_proto_init() {
	if File_gommerce_utils_v1_utils_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gommerce_utils_v1_utils_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextHexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextHexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextInt64Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextInt64Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDBNowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDBNowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRedisNowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRedisNowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUTCNowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUTCNowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocalNowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocalNowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchLocalNowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gommerce_utils_v1_utils_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchLocalNowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gommerce_utils_v1_utils_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_gommerce_utils_v1_utils_proto_goTypes,
		DependencyIndexes: file_gommerce_utils_v1_utils_proto_depIdxs,
		MessageInfos:      file_gommerce_utils_v1_utils_proto_msgTypes,
	}.Build()
	File_gommerce_utils_v1_utils_proto = out.File
	file_gommerce_utils_v1_utils_proto_rawDesc = nil
	file_gommerce_utils_v1_utils_proto_goTypes = nil
	file_gommerce_utils_v1_utils_proto_depIdxs = nil
}
