// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gommerce/pns/v1beta/pns.proto

package pns_v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gommerce_pns_v1beta_pns_proto protoreflect.FileDescriptor

const file_gommerce_pns_v1beta_pns_proto_rawDesc = "" +
	"\n" +
	"\x1dgommerce/pns/v1beta/pns.proto\x12\x13gommerce.pns.v1betaB\x82\x01\n" +
	"#io.choral.gommerce.proto.pns.v1betaZ?github.com/choral-io/gommerce-protobuf-go/pns/v1beta;pns_v1beta\xaa\x02\x19Gommerce.Proto.PNS.V1Betab\x06proto3"

var file_gommerce_pns_v1beta_pns_proto_goTypes = []any{}
var file_gommerce_pns_v1beta_pns_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gommerce_pns_v1beta_pns_proto_init() }
func file_gommerce_pns_v1beta_pns_proto_init() {
	if File_gommerce_pns_v1beta_pns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gommerce_pns_v1beta_pns_proto_rawDesc), len(file_gommerce_pns_v1beta_pns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gommerce_pns_v1beta_pns_proto_goTypes,
		DependencyIndexes: file_gommerce_pns_v1beta_pns_proto_depIdxs,
	}.Build()
	File_gommerce_pns_v1beta_pns_proto = out.File
	file_gommerce_pns_v1beta_pns_proto_goTypes = nil
	file_gommerce_pns_v1beta_pns_proto_depIdxs = nil
}
